packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  msw: true
  sharp: true
  drizzle-kit: true
  drizzle-orm: true
minimumReleaseAgeExclude:
  - bullmq@5.77.1
