services:
  traefik:
    image: traefik:v3.6.1
    restart: unless-stopped

    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=app-network
      - --entrypoints.web.address=:80

    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - app-network

networks:
  app-network:
    external: true
