services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    command: >
      redis-server
      --appendonly yes
      --requirepass WyXNQPXTpQkPDUDqna7LomMgfn53Rsec

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  redis-data:
