services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD}

    volumes:
      - redis-data:/data

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

    ports:
      - "6379:6379"

networks:
  app-network:
    external: true

volumes:
  redis-data:
